# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='descriptiion',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
