# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_trip_descriptiion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='descriptiion',
            new_name='description',
        ),
    ]
