# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170829_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='name',
            new_name='destination',
        ),
    ]
