# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-03 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170829_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_by', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adding', to='login.User')),
                ('liked_by', models.ManyToManyField(related_name='likes', to='login.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='Booked_by',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='added_by',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
